"""Tests for scripts/poetry_install.py helpers."""

from __future__ import annotations

from pathlib import Path

import pytest
from scripts.poetry_install import Poetry2LockReader, RootVenvInstaller


def _write_lock(path: Path, *, lock_version: str, body: str) -> None:
    path.write_text(
        f"""\
# This file is automatically @generated by Poetry 2.4.1

[[package]]
{body}

[metadata]
lock-version = "{lock_version}"
python-versions = ">=3.12,<3.14"
""",
        encoding="utf-8",
    )


def test_main_pins_skips_directory_and_non_main(tmp_path: Path) -> None:
    lock = tmp_path / "poetry.lock"
    _write_lock(
        lock,
        lock_version="2.1",
        body="""\
name = "fastapi"
version = "0.115.0"
groups = ["main"]
files = []

[[package]]
name = "ruff"
version = "0.6.0"
groups = ["dev"]
files = []

[[package]]
name = "autopulse-shared"
version = "0.1.0"
groups = ["main"]
files = []
develop = true

[package.source]
type = "directory"
url = "../../shared"
""",
    )
    pins = Poetry2LockReader().main_pins(lock)
    assert pins == {"fastapi": "0.115.0"}


def test_main_pins_rejects_poetry1_lock(tmp_path: Path) -> None:
    lock = tmp_path / "poetry.lock"
    _write_lock(
        lock,
        lock_version="1.1",
        body="""\
name = "fastapi"
version = "0.115.0"
category = "main"
optional = false
files = []
""",
    )
    with pytest.raises(SystemExit, match="Poetry 2"):
        Poetry2LockReader().main_pins(lock)


def test_merge_service_pins_detects_conflicts(tmp_path: Path) -> None:
    enrichment = tmp_path / "enrichment"
    pricer = tmp_path / "pricer"
    enrichment.mkdir()
    pricer.mkdir()
    _write_lock(
        enrichment / "poetry.lock",
        lock_version="2.1",
        body="""\
name = "pydantic"
version = "2.5.0"
groups = ["main"]
files = []
""",
    )
    _write_lock(
        pricer / "poetry.lock",
        lock_version="2.1",
        body="""\
name = "pydantic"
version = "2.7.0"
groups = ["main"]
files = []
""",
    )
    installer = RootVenvInstaller(services=(enrichment, pricer))
    with pytest.raises(SystemExit, match="Conflicting locked versions"):
        installer.merge_service_pins()
